export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOAD_USER = 'LOAD_USER';

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const FETCH_RENTALS = 'FETCH_RENTALS';
export const CREATE_RENTAL = 'CREATE_RENTAL';

export const FETCH_RENTAL_BY_ID = 'FETCH_RENTAL_BY_ID';
export const IS_FETCHING_RENTAL = 'IS_FETCHING_RENTAL';
export const UNMOUNT_RENTAL = 'UNMOUNT_RENTAL';

export const FETCH_RENTERS = 'FETCH_RENTERS';
export const CREATE_RENTER = 'CREATE_RENTER';

export const FETCH_OWNERS = 'FETCH_OWNERS';
export const CREATE_OWNER = 'CREATE_OWNER';
